### PR TITLE
Add basic Dockerfile for building the image on Docker Hub

### PR DESCRIPTION
**Pull request by warden**

### CODE REVIEW

**Comment by warden** [comment]
@giventocode there you go!

**Comment by cicorias** [comment]
what is then intent with this Docker file - it just seems to create an image, never pulls in this  repos code, etc. to make the container specific or usable for this tool. eg. I  would expect at least the commands here:
https://blobporter.readthedocs.io/en/latest/gettingstarted.html#linux 

```
wget -O bp_linux.tar.gz https://github.com/Azure/blobporter/releases/download/v0.6.15/bp_linux.tar.gz
tar -xvf bp_linux.tar.gz linux_amd64/blobporter
chmod +x ~/linux_amd64/blobporter
```
Along with an `ENTRYPOINT` of `./blobporter` so I can pass the CLI options.

**Comment by warden** [comment]
The intent here is to auto-build this image in DockerHub.
👍 for entrypoint.

**Comment by warden** [comment]
@cicorias done!

**Comment by warden** [comment]
@cicorias  will that get merged or should I close it?

**Pull request closed without merging**
