### PR TITLE
feat(proxy): Support proxy envvars

### PR DESCRIPTION
**Pull request by sylus**
I wasn't able to get blobporter with our proxy without these adjustments.

Thanks for the awesomo project!

### CODE REVIEW

**Comment by giventocode** [comment]
@sylus thanks for the contribution, this is very helpful. Do you mind submitting the PR to the dev branch?

**Comment by sylus** [comment]
There you go :)

Really like blobporter can believe how fast it is ^_^

**Comment by giventocode** [comment]
Thank for the PR.

**Comment by sylus** [comment]
Hey @giventocode, I didn't see this merged, was there something else you needed me to do? :)

**Pull request merged**
